### PR TITLE
Skip v2

### PR DESCRIPTION
**Pull request by neg**

### CODE REVIEW

**Review by rical — COMMENTED** [review]
Great to have test suites for all skip scenarios. However, I would prefer to have all unit tests in `auto.yaml` and only run 9pm.py once. This might mean only including the non-failure skips in the main auto suite. This way skip will be somewhat exercised in the `auto.yaml` suite without polluting the output too much and we avoid marking the execution as fail. The `ok-skip-fail-states.yaml` suite which contains failures can be useful to have for debugging, it doesn't need to be part of the "auto-tests".

Side note: have you seen the suite (failure) masking feature? It might be useful here, check `unit_tests/harness/onfail.tcl`

**Comment by neg** [comment]
I'm OK with moving the ok-skip-states.yaml and ok-states.yaml to auto.yaml but this would cause the whole auto.yaml run to be flagged as skipped, is this an OK solution for you?

**Comment by rical** [comment]
I will add support for skip suite-masking, so it's okey if the top node is yellow for now. Just run the non-error skip suites directly from auto.yaml (you will need to modify your `$argv` implementation a bit, or create separate test-cases).

**Comment by neg** [comment]
Sounds good!

**Comment by neg** [comment]
Superseded.

**Pull request closed without merging**
